import {
  BookOpen,
  Calculator,
  FlaskConical,
  Globe2,
  Languages,
  BookMarked,
} from "lucide-react";

const subjectColors = {
  gujarati: "blue",
  mathematics: "orange",
  english: "green",
  hindi: "yellow",
  evs: "emerald",
  science: "purple",
  socialScience: "red",
  sanskrit: "indigo",
} as const;

export const subjectsByStandard = {
  1: [
    {
      id: "gujarati",
      title: "Gujarati",
      icon: Languages,
      color: subjectColors.gujarati,
      href: "/subjects/1/gujarati",
    },
    {
      id: "mathematics",
      title: "Mathematics",
      icon: Calculator,
      color: subjectColors.mathematics,
      href: "/subjects/1/mathematics",
    },
    {
      id: "english",
      title: "English",
      icon: BookOpen,
      color: subjectColors.english,
      href: "/subjects/1/english",
    },
  ],

  2: [
    {
      id: "gujarati",
      title: "Gujarati",
      icon: Languages,
      color: subjectColors.gujarati,
      href: "/subjects/2/gujarati",
    },
    {
      id: "mathematics",
      title: "Mathematics",
      icon: Calculator,
      color: subjectColors.mathematics,
      href: "/subjects/2/mathematics",
    },
    {
      id: "english",
      title: "English",
      icon: BookOpen,
      color: subjectColors.english,
      href: "/subjects/2/english",
    },
  ],

  3: [
    {
      id: "gujarati",
      title: "Gujarati",
      icon: Languages,
      color: subjectColors.gujarati,
      href: "/subjects/3/gujarati",
    },
    {
      id: "mathematics",
      title: "Mathematics",
      icon: Calculator,
      color: subjectColors.mathematics,
      href: "/subjects/3/mathematics",
    },
    {
      id: "english",
      title: "English",
      icon: BookOpen,
      color: subjectColors.english,
      href: "/subjects/3/english",
    },
    {
      id: "evs",
      title: "Environmental Studies",
      icon: Globe2,
      color: subjectColors.evs,
      href: "/subjects/3/evs",
    },
    {
      id: "hindi",
      title: "Hindi",
      icon: BookMarked,
      color: subjectColors.hindi,
      href: "/subjects/3/hindi",
    },
  ],

  4: [
    {
      id: "gujarati",
      title: "Gujarati",
      icon: Languages,
      color: subjectColors.gujarati,
      href: "/subjects/4/gujarati",
    },
    {
      id: "mathematics",
      title: "Mathematics",
      icon: Calculator,
      color: subjectColors.mathematics,
      href: "/subjects/4/mathematics",
    },
    {
      id: "english",
      title: "English",
      icon: BookOpen,
      color: subjectColors.english,
      href: "/subjects/4/english",
    },
    {
      id: "evs",
      title: "Environmental Studies",
      icon: Globe2,
      color: subjectColors.evs,
      href: "/subjects/4/evs",
    },
    {
      id: "hindi",
      title: "Hindi",
      icon: BookMarked,
      color: subjectColors.hindi,
      href: "/subjects/4/hindi",
    },
  ],

  5: [
    {
      id: "gujarati",
      title: "Gujarati",
      icon: Languages,
      color: subjectColors.gujarati,
      href: "/subjects/5/gujarati",
    },
    {
      id: "mathematics",
      title: "Mathematics",
      icon: Calculator,
      color: subjectColors.mathematics,
      href: "/subjects/5/mathematics",
    },
    {
      id: "english",
      title: "English",
      icon: BookOpen,
      color: subjectColors.english,
      href: "/subjects/5/english",
    },
    {
      id: "evs",
      title: "Environmental Studies",
      icon: Globe2,
      color: subjectColors.evs,
      href: "/subjects/5/evs",
    },
    {
      id: "hindi",
      title: "Hindi",
      icon: BookMarked,
      color: subjectColors.hindi,
      href: "/subjects/5/hindi",
    },
  ],

  6: [
    {
      id: "gujarati",
      title: "Gujarati",
      icon: Languages,
      color: subjectColors.gujarati,
      href: "/subjects/6/gujarati",
    },
    {
      id: "mathematics",
      title: "Mathematics",
      icon: Calculator,
      color: subjectColors.mathematics,
      href: "/subjects/6/mathematics",
    },
    {
      id: "science",
      title: "Science",
      icon: FlaskConical,
      color: subjectColors.science,
      href: "/subjects/6/science",
    },
    {
      id: "english",
      title: "English",
      icon: BookOpen,
      color: subjectColors.english,
      href: "/subjects/6/english",
    },
    {
      id: "hindi",
      title: "Hindi",
      icon: BookMarked,
      color: subjectColors.hindi,
      href: "/subjects/6/hindi",
    },
    {
      id: "social-science",
      title: "Social Science",
      icon: Globe2,
      color: subjectColors.socialScience,
      href: "/subjects/6/social-science",
    },
    {
      id: "sanskrit",
      title: "Sanskrit",
      icon: Languages,
      color: subjectColors.sanskrit,
      href: "/subjects/6/sanskrit",
    },
  ],

  7: [
    {
      id: "gujarati",
      title: "Gujarati",
      icon: Languages,
      color: subjectColors.gujarati,
      href: "/subjects/7/gujarati",
    },
    {
      id: "mathematics",
      title: "Mathematics",
      icon: Calculator,
      color: subjectColors.mathematics,
      href: "/subjects/7/mathematics",
    },
    {
      id: "science",
      title: "Science",
      icon: FlaskConical,
      color: subjectColors.science,
      href: "/subjects/7/science",
    },
    {
      id: "english",
      title: "English",
      icon: BookOpen,
      color: subjectColors.english,
      href: "/subjects/7/english",
    },
    {
      id: "hindi",
      title: "Hindi",
      icon: BookMarked,
      color: subjectColors.hindi,
      href: "/subjects/7/hindi",
    },
    {
      id: "social-science",
      title: "Social Science",
      icon: Globe2,
      color: subjectColors.socialScience,
      href: "/subjects/7/social-science",
    },
    {
      id: "sanskrit",
      title: "Sanskrit",
      icon: Languages,
      color: subjectColors.sanskrit,
      href: "/subjects/7/sanskrit",
    },
  ],

  8: [
    {
      id: "gujarati",
      title: "Gujarati",
      icon: Languages,
      color: subjectColors.gujarati,
      href: "/subjects/8/gujarati",
    },
    {
      id: "mathematics",
      title: "Mathematics",
      icon: Calculator,
      color: subjectColors.mathematics,
      href: "/subjects/8/mathematics",
    },
    {
      id: "science",
      title: "Science",
      icon: FlaskConical,
      color: subjectColors.science,
      href: "/subjects/8/science",
    },
    {
      id: "english",
      title: "English",
      icon: BookOpen,
      color: subjectColors.english,
      href: "/subjects/8/english",
    },
    {
      id: "hindi",
      title: "Hindi",
      icon: BookMarked,
      color: subjectColors.hindi,
      href: "/subjects/8/hindi",
    },
    {
      id: "social-science",
      title: "Social Science",
      icon: Globe2,
      color: subjectColors.socialScience,
      href: "/subjects/8/social-science",
    },
    {
      id: "sanskrit",
      title: "Sanskrit",
      icon: Languages,
      color: subjectColors.sanskrit,
      href: "/subjects/8/sanskrit",
    },
  ],
} as const;